create database miniproject;
show databases;
use miniproject;

CREATE TABLE USERSINFO(
USER_NAME varchar(20) NOT NULL PRIMARY KEY,
FIRST_NAME VARCHAR(25),
LAST_NAME VARCHAR(25),
MOBILE_NUMBER int(10),
DOB INT(10),
GENDER TINYINT(1) NOT NULL,
MONTHLY_INCOME int(15),
PASSWORDS VARCHAR(255) NOT NULL

);

INSERT INTO USERSINFO
	(USER_NAME, FIRST_NAME, LAST_NAME, MOBILE_NUMBER, DOB, GENDER,MONTHLY_INCOME,PASSWORDS) 
    VALUES ('user1', 'John', 'Doe', 1234567890, 19900101, 1, 5000, 'hashedpassword1');


SELECT * FROM USERSINFO;


CREATE TABLE ACCOUNT_INFO(
USER_NAME varchar(20) NOT NULL ,
BALANCE INT(10) NOT NULL,

FOREIGN KEY (USER_NAME) REFERENCES USERSINFO(USER_NAME)
);


UPDATE ACCOUNT_INFO
SET BALANCE = 1000
WHERE USER_NAME = 'user1';

SELECT * FROM ACCOUNT_INFO;

CREATE TABLE EXPENSE_TRACKER(
USER_NAME varchar(20) NOT NULL ,
DESCRIPTION_OF_EXPENSE varchar(50) NOT NULL,
AMOUNT INT(25),
TIME_STAMP DATETIME,

FOREIGN KEY (USER_NAME) REFERENCES USERSINFO(USER_NAME)
);

INSERT INTO EXPENSE_TRACKER(DESCRIPTION_OF_EXPENSE,AMOUNT,TIME_STAMP,USER_NAME)
VALUES();


